apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kiii-project

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - db-statefulset.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml
