apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: kiii-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: galic/backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
        #here i dont know which name to use
#          value: postgresql://postgres:password@db:5432/fullstack_app
          value: postgres://kiii_user:kiii_password@db:5432/kiii_db
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: kiii-project
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000