apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: kiii-project
type: Opaque
stringData:
#  POSTGRES_DB: "fullstack_app"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "password"
  